### ISSUE TITLE
Probr.io - Fix broken link for Privacy Policy

### ISSUE THREAD

**Issue by lluuiissoo** [probr/probr-core#32]
Privacy Policy link in footer gives 404 (citihub.com/privacy)
Link should be fixed. Get confirmation from management where the privacy policy is.

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/13456333/164147793-98228e32-40f2-4e87-aacf-14643c9bb2d8.png">

**Comment by eddie-knight** [comment]
Resolved this by removing the link
